// SPDX-License-Identifier: MIT
pragma solidity ^0.8.25;

import { EoaProof } from "./circuits/IVerifier.sol"; /// @dev - This SC is generated by ZK circuit (in Circom)

/// @notice Struct to hold the email authentication/authorization message.
struct EoaAuthMsg {
    /// @notice The EOA proof containing the zk proof and other necessary information for the EOA verification by the Verifier contract.
    EoaProof proof; /// @dev - This EoaProof is imported from the Verifier.sol
}

interface IEoaAuth {
    function authEoa(EoaAuthMsg memory eoaAuthMsg, uint256[34] calldata pubSignals) external; /// @dev - The "EoaAuthMsg" struct would include the "EoaProof proof" property, meaning that the proof (EmailProof) will be registered via this authEmail() function.
}