#!/bin/sh

CYAN='\033[0;36m'
RED='\033[0;31m'
NC='\033[0m' # No Colour

check_fmt () {
    if ! pnpm fmt:check > /dev/null 2>&1; then
        echo "${RED}Commit error! Cannot commit unformatted code!${NC}"
        echo "Formatting errors found. Please format the code via ${CYAN}'pnpm fmt'${NC}!"
        exit 1
    fi
}

check_fmt