name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Check formatting
        run: pnpm fmt:check

      - name: Check linting
        run: pnpm lint:check

  build:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Show Foundry config
        run: forge config

      - name: Build contracts
        run: forge build

      - name: Save build artifacts cache
        uses: actions/cache/save@v4
        with:
          key: build-artifacts-${{ github.sha }}
          path: |
            cache
            out

  test:
    needs: ["build"]
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Restore the cached build and the node modules
        uses: actions/cache/restore@v4
        with:
          key: build-artifacts-${{ github.sha }}
          path: |
            cache
            out

      - name: Test DEFAULT account
        run: forge test --threads 1 --match-path "test/**/*.sol"
        env:
          ACCOUNT_TYPE: DEFAULT

      - name: Test SAFE account
        run: forge test --threads 1 --match-path "test/**/*.sol"
        env:
          ACCOUNT_TYPE: SAFE

      - name: Test KERNEL account
        run: forge test --threads 1 --match-path "test/**/*.sol"
        env:
          ACCOUNT_TYPE: KERNEL

      - name: Test NEXUS account
        run: forge test --threads 1 --match-path "test/**/*.sol"
        env:
          ACCOUNT_TYPE: NEXUS
