name: "Build a Forge project"

on:
  workflow_call:
    inputs:
      cache-path:
        default: |
          cache
          node_modules
          out
          out-optimized
        required: false
        type: "string"

      save-cache:
        default: true
        required: false
        type: boolean

jobs:
  forge-build:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v4"

      - name: "Install Foundry"
        uses: "foundry-rs/foundry-toolchain@v1.3.1"

      - name: "Install NodeJS"
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9.0.6
          run_install: false

      - name: "Install the Node.js dependencies"
        run: "pnpm install"

      - name: "Show the Forge config"
        run: "forge config"

      - name: "Build the production contracts"
        run: "forge build"

      - name: "Cache node__odules"
        if: ${{ inputs.save-cache }}
        uses: "actions/cache/save@v4"
        with:
          key: "build-and-modules-${{ github.sha }}"
          path: node_modules

      - name: "Cache the contracts and the node modules so that they can be re-used by the other jobs"
        if: ${{ inputs.save-cache }}
        uses: "actions/cache/save@v4"
        with:
          key: "build-and-modules-${{ github.sha }}"
          path: out

      - name: "Add summary"
        run: |
          echo "## Build result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
