name: test

on:
  push:
  pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  build:
    uses: "./.github/workflows/forge-build.yaml"

  test-multi-account:
    needs: ["build"]
    uses: "./.github/workflows/forge-test-multi-account.yaml"
    with:
      foundry-fuzz-runs: 5000
      foundry-profile: "test"
      match-path: "test/**/*.sol"
